---
- name: install docker
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Install docker
      yum:
        name: docker
        state: present
      register: ins_stat
    - name: Start docker service
      service:
        name: docker
        state: started
      register: doc_ser
    - name: Debugging success status
      debug:
        msg: "Docker service running successfully"
      when: doc_ser.status.SubState == "running"
    - name: Debugging failure status
      debug:
        msg: "Docker service failed to run"
      when: doc_ser.status.SubState != "running"

